### PR TITLE
implemented WheelMultiController

### PR DESCRIPTION
**Pull request by mathias-luedtke**
WheelController which does not use the steer position controller, but command the postion target instead.

Not tested.

### CODE REVIEW

**Comment by mathias-luedtke** [comment]
I am not that happy with the code layout, but it's okay for first tests.

**Comment by ipa-fxm** [comment]
First try loading the `cob_omni_drive_controller/WheelMultiController`:

base_controller.yaml:
```
## joint_names
joint_names: [fl_caster_rotation_joint, fl_caster_r_wheel_joint, fr_caster_rotation_joint, fr_caster_r_wheel_joint, b_caster_rotation_joint, b_caster_r_wheel_joint]

## joint_state_controller
joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

## twist_controller wheel-multi
twist_controller_wheel_multi:
  type: cob_omni_drive_controller/WheelMultiController
  required_drive_mode: 2  # velocity
  required_drive_modes:
    fl_caster_rotation_joint: 1  # position
    b_caster_rotation_joint: 1   # position
    fr_caster_rotation_joint: 1  # position
  #max_rot_velocity: 1.0
  #max_trans_velocity: 1.0
  pub_divider: 1
  timeout: 0.5

  wheels: &wheels # start front left, counter-clockwise for base_drive_chain compatibility
    - steer: fl_caster_rotation_joint
      drive: fl_caster_r_wheel_joint
    - steer: b_caster_rotation_joint
      drive: b_caster_r_wheel_joint
      steer_neutral_position: -180.0
    - steer: fr_caster_rotation_joint
      drive: fr_caster_r_wheel_joint

## twist_controller
twist_controller:
  type: cob_omni_drive_controller/WheelController
  required_drive_mode: 3
  #max_rot_velocity: 1.0
  #max_trans_velocity: 1.0
  pub_divider: 1
  timeout: 0.5

  defaults: # default settings for all wheels, can per overwritten per wheel
    steer_ctrl: # Parameters for tuning Impedance-Controller
      spring: 15.0
      damp: 2.75
      virt_mass: 0.1
      d_phi_max: 10.0
      dd_phi_max: 40.0
  wheels: *wheels

## odometry_controller
odometry_controller:
  type: cob_omni_drive_controller/OdometryController
  publish_rate: 50
  frame_id: "/odom_combined"
  child_frame_id: "/base_footprint"
  cov_pose: 0.1
  cov_twist: 0.1
  wheels: *wheels
```



shows the following error:
```
[INFO] [1487333658.122055]: ...<<base>> is <<init>>
[ INFO] [1487333658.124910526]: Recover base
[INFO] [1487333658.138721]: <<recover>> <<base>>
[INFO] [1487333658.154278]: Wait for <<base>> to <<recover>>...
[ INFO] [1487333658.161700635]: Recovering XXX
[INFO] [1487333658.162833]: ...<<base>> is <<recover>>
Loaded joint_state_controller
[ERROR] [1487333658.257252456]: steer_ctrl not found
[ERROR] [1487333658.257363749]: Failed to initialize the controller
[ERROR] [1487333658.257429643]: Initializing controller 'twist_controller_wheel_multi' failed
Error when loading twist_controller_wheel_multi
Loaded odometry_controller
Started ['joint_state_controller'] successfully
[ERROR] [1487333658.304438991]: Could not start controller with name twist_controller_wheel_multi because no controller with this name exists
Error when starting  ['twist_controller_wheel_multi']
Started ['odometry_controller'] successfully
```

**Comment by fmessmer** [comment]
[this base_controller.yaml](https://raw.githubusercontent.com/ipa-fxm/cob_robots/kinetic/unified-cob4-base-cob4-8-wheel-multi-controller/cob_hardware_config/common/cob4_base_controller.yaml) works

Still I observe two issues:
 - and we still need to set the `default/steer_ctrl` parameters - thought those are not needed in this mixed mode
 - as I'm using the unified_base structure, I get emergency stop when driving with "boost button" from joystick
 - the steer joints seem to be commanded to absolute position and not correctly cropped to [0...360°] at least "some" of the steer_joints rotate more than 360° sometimes..

**Comment by mathias-luedtke** [comment]
> as I'm using the unified_base structure, I get emergency stop when driving with "boost button" from joystick

Have you tried with https://github.com/ipa320/cob_common/pull/211?

> the steer joints seem to be commanded to absolute position and not correctly cropped to [0...360°] at least "some" of the steer_joints rotate more than 360° sometimes..

You could try `pos_to_device: "norm(rint(rad2deg(pos)*1000),0,360000)"` to keep it in [0,360).

**Comment by mathias-luedtke** [comment]
Velocity settings:
* `607F` - max profile velocity / VH[2] maximum for mode 3 and 1
* `6081` target velocity of ramp in mode 1

**Comment by fmessmer** [comment]
limits as read from elmo:
```
1
VH[2]: 7896003
2
VH[2]: 1142862
3
VH[2]: 7896003
4
VH[2]: 1142862
5
VH[2]: 7896003
6
VH[2]: 1142862

1
SP: 1000000
2
SP: 1000000
3
SP: 10000000
4
SP: 10000000
5
SP: 10000000
6
SP: 10000000
```

**Comment by fmessmer** [comment]
Boost Error Log:
```
EMCY: 82#20FF050000000000
EMCY: 85#20FF050000000000
EMCY: 81#20FF050000000000
EMCY: 83#20FF050000000000
EMCY: 84#20FF050000000000
EMCY: 86#20FF050000000000
[ERROR] [1487339239.115009692]: Node has emergency error; Node has emergency error; Node has emergency error; Node has emergency error; Node has emergency error; Node has emergency error
```

**Comment by mathias-luedtke** [comment]
The safety controller is just kicking in ;)

**Comment by fmessmer** [comment]
velocity is ok now that I moved further away from the wall :wink: 

Here is a plot for the steer_joints (joint_states and target_position) for a case where the wheels start to oscillate:

robot_wheel_multi_oscilating

There is a lot of `angles::normalize_angle()` and `atan4quad()`/`atan2()` within `updateCtrl()`

**Comment by fmessmer** [comment]
I think we need to derive the `updateCtrl()` for WheelController, i.e. all joints velocity mode, and WheelMultiController, i.e. drive velocity mode, steer position mode.

Then we also could get rid of the fact that steer_ctrl parameters are needed for WheelMultiController...

**Comment by mathias-luedtke** [comment]
already on it :)

**Comment by fmessmer** [comment]
We will not merge this one but continue testing the refactored code from #140

**Pull request closed without merging**
