### PR TITLE
remove cob_trajectory_controller

### PR DESCRIPTION
**Pull request by floweisshardt**
- fixes parts of https://github.com/ipa320/care-o-bot/issues/46
- needed for https://github.com/ipa320/cob_robots/pull/695

### CODE REVIEW

**Comment by ipa-fxm** [comment]
do not merge
raw3-1 still uses it: https://github.com/ipa320/cob_robots/blob/indigo_dev/cob_bringup/robots/raw3-1.xml#L57-L61

**Review by fmessmer — CHANGES_REQUESTED** [review]
**Do not merge**
raw3-1 still uses it: https://github.com/ipa320/cob_robots/blob/indigo_dev/cob_bringup/robots/raw3-1.xml#L57-L61

**Comment by ipa-rmb** [comment]
What are the options? Have a legacy repository for such things? Using other hardware for the raw3-1 torso?

**Comment by floweisshardt** [comment]
I prefer using other (CanOpen ready) hardware.

**Comment by ipa-rmb** [comment]
We decided in the meeting to install a newer hardware. I will have to discuss this with @ipa-bfb and mechanics.

**Comment by fmessmer** [comment]
How do we deal with this?
See https://github.com/ipa320/care-o-bot/issues/46#issuecomment-327392494

**Comment by fmessmer** [comment]
let's keep these packages for the time being...we can still remove them once they require more maintenance effort in the future

**Pull request closed without merging**
