### PR TITLE
Feature/1238 joint trajectory controller emulator linear interpolation

### PR DESCRIPTION
**Pull request by lindemeier**
Replaced step function with linear interpolation:
* sampling each joint state in fixed time steps using linear interpolation of current and next joint state goal
* using rospy loop rate instead of timer
* velocity computed per joint
* added preempt
* added service reset joint_states

### CODE REVIEW

**Review by floweisshardt — DISMISSED** [review]
looks good.

tested: 
- interpolation
- preemption with cancel
- preemption with new goal

**Review by benmaidel — DISMISSED** [review]

**Review by floweisshardt — CHANGES_REQUESTED** [review]
- [x] resetting joint states tested: OK
- [x] joint velocities are not resetted to `0` after last trajectory point (robot is not moving anymore).

**Comment by lindemeier** [comment]
Added requested setting to zero after reaching final pose

**Review by floweisshardt — APPROVED** [review]

**Comment by floweisshardt** [comment]
tested resetting joint velocities: OK

**Pull request merged**
