### PR TITLE
added VelocityEstimator with randomized tests

### PR DESCRIPTION
**Pull request by mathias-luedtke**
Estimate velocity if measured velocity is too noisy or faulty.
Added parameter "defaults/estimate_velocity_with_overflow" and per-joint "estimate_velocity_with_overflow/JOINT_NAME".

Zero (default) means no estimation.
Value < Zero: Estimation without overflow.
Vaue > Zero: The postion values must be in the range [-value, value) and value must be greater than twice the maximum velocity.

### CODE REVIEW

**Comment by fmessmer** [comment]
Can't say much about this PR...
@ipa-josh @ipa-mig: Any comments/feedback?

**Comment by mgruhler** [comment]
i know what it should do, but have never seen it run

**Comment by mathias-luedtke** [comment]
Will be tested on cob4-4 next week.
A modified version was already tested on cob4-6.

**Comment by fmessmer** [comment]
@ipa-mdl
This PR cannot be merged anymore.
In case it still should be merged into ipa320, could you please update this PR or close it?

**Comment by mathias-luedtke** [comment]
It cannot be merged anymore because of https://github.com/ipa-mdl/cob_control/commit/c8d91a59e433bcf48ae67c45ee7064eff2e884c6.
However, we don't need this PR anymore.
I will file a new one after our tests next week.

**Pull request closed without merging**
