### PR TITLE
Added Eigen3 Indigo/Kinetic compatibility

### PR DESCRIPTION
**Pull request by destogl**
Maybe would make sense to cherry-pick it also to indigo-dev.

### CODE REVIEW

**Comment by mgruhler** [comment]
@ipa-bnm please doublecheck and compare/integrate with #115

**Comment by benmaidel** [comment]
I like this better than in this PR https://github.com/ipa320/cob_control/pull/115/files because it supports Eigen2 and Eigen3. But why switch from EIGEN_INCLUDE_DIRS to EIGEN3_INCLUDE_DIRS definition? It is not necessary. If Eigen3 is not found we just find_package Eigen and if Eigen3 is found set EIGEN3_INCLUDE_DIR to EIGEN_INCLUDE_DIRS...

**Comment by benmaidel** [comment]
like this:
```
find_package(Eigen3)
if(NOT EIGEN3_FOUND)
  # Fallback to cmake_modules
  find_package(cmake_modules REQUIRED)
  find_package(Eigen REQUIRED)
  add_definitions(${EIGEN_DEFINITIONS})
else()
  set(EIGEN_INCLUDE_DIRS ${EIGEN3_INCLUDE_DIR})
  add_definitions(${EIGEN3_DEFINITIONS})
endif()
```

**Comment by destogl** [comment]
This is also possible. I just basically copy-pasted migration example from ROS-wiki.

I you wish I can update it.

**Comment by fmessmer** [comment]
Not sure, but do we need this for `indigo_dev`, too?

**Comment by benmaidel** [comment]
Not necessarily. We could cherry pick from `kinetic_dev`.

**Pull request merged**
