### PR TITLE
Cob undercarriage ctrl node

### PR DESCRIPTION
**Pull request by mathias-luedtke**
This PR includes https://github.com/ipa320/cob_driver/pull/206 and fixed the open issues:
- migrated to new cob_omni_drive_controller
- migrated to new param format
- migrated to OdometryTracker

I have deciced to create a new package instead of merging it into cob_omni_drive_controller because of the dependencies.

Was not yet tested on real hardware!

### CODE REVIEW

**Comment by mgruhler** [comment]
@olgen2013 FYI

looks okay so far. Tests on hardware need to be made before merge!

**Comment by floweisshardt** [comment]
visual review: OK, still waiting for HW tests

**Comment by fmessmer** [comment]
On which platforms will this be tested?
If this is meant to be used with a raw as well, I'd like to see a confirmed HW test with one of them...
Please check back again with @ipa-mig and/or @olgen2013...

**Comment by mathias-luedtke** [comment]
Should be used on all non-ros_canopen bases (cob4-1, cob4-2, raw3-\* and cob3-*).
We will try to migrate all bases to ros_canopen later.

**Comment by fmessmer** [comment]
@ipa-mdl
Is this PR still up-to-date? After an `ok` from your side, I will merge this....

**Comment by mathias-luedtke** [comment]
This version was not yet tested on real hardware, but is still up-to-date.

**Comment by fmessmer** [comment]
Ok, so waiting for your `ok` **after** real hardware test...?

**Comment by fmessmer** [comment]
With https://github.com/ipa320/cob_robots/pull/417 being available and tested on HW, this PR is obsolete, right?
Old bases either follow https://github.com/ipa320/cob_robots/pull/417 or stick with the old undercarriage_control, correct?

**Comment by floweisshardt** [comment]
correct, we can close this one

**Comment by fmessmer** [comment]
@ipa-mdl please close in case you agree

**Comment by floweisshardt** [comment]
talking to @ipa-mdl we decided to merge this one as it works for cob3s and doesn't harm all other implementations.

**Pull request merged**
