### PR TITLE
Correction of velocity collision filter

### PR DESCRIPTION
**Pull request by destogl**
From hydro there is change in [costmap_2d node](http://wiki.ros.org/costmap_2d) so that otuput is [OccupancyGrid](http://docs.ros.org/hydro/api/nav_msgs/html/msg/OccupancyGrid.html) instead of [GridCell](http://docs.ros.org/hydro/api/nav_msgs/html/msg/GridCells.html).

### CODE REVIEW

**Comment by fmessmer** [comment]
removing the cob_lookat_controller files is ok...although they are already removed in ipa320/cob_control...maybe merge with latest indigo_dev again to clean up...

@ipa-mig please review the changes in cob_collision_velocity_filter

**Comment by destogl** [comment]
done

**Comment by floweisshardt** [comment]
visual review: OK, waiting for feedback from @ipa-mig

**Comment by mgruhler** [comment]
Thanks for fixing this. I knew about this issue, but didn't get around to fixing it myself...
Has this been tested on a robot already?

Visual review :ok:

**Comment by destogl** [comment]
Yes, It is tested on raw3-5

**Comment by mgruhler** [comment]
perfect.
Ready to be merged... :-)

**Pull request merged**
