### PR TITLE
[Melodic] release fixes

### PR DESCRIPTION
**Pull request by fmessmer**
ref https://github.com/ipa320/care-o-bot/issues/52

 - https://github.com/ipa320/cob_control/pull/209/commits/c2f8cb1ffa052940942a555d85731a13aae7ee2f: :arrow_right: #210 
    http://build.ros.org/job/Mbin_uB64__cob_twist_controller__ubuntu_bionic_amd64__binary/5/consoleText
 - https://github.com/ipa320/cob_control/pull/209/commits/0dfd3f0d00ad7fc91be3043ac188efab84a7dba3: 
    http://build.ros.org/job/Mbin_ds_dS64__cob_obstacle_distance__debian_stretch_amd64__binary/5/console

### CODE REVIEW

**Comment by fmessmer** [comment]
@ipa-jba @ipa-fez @benmaidel 
could you help me with the second error?
http://build.ros.org/job/Mbin_ds_dS64__cob_obstacle_distance__debian_stretch_amd64__binary/5/console

**Comment by ipa-fez** [comment]
The problem seems to be that boost shared_ptrs and std shared ptrs are being mixed. we're trying to cast the geometry from a std shared ptr of one type to a boost shared_ptr of another type, but we can only cast it to a std shared_ptr of a different type.

**Comment by ipa-fez** [comment]
More concrete: `PtrGeometry_t` seems to be a `std::shared_ptr` for some reason while everything else is `boost::shared_ptr`

**Comment by fmessmer** [comment]
yap, in `kinetic`, `urdf` is using `boost::shared` while in `melodic` `urdf` uses `std::shared`

I'm resolving this by using a new `melodic_dev` branch...it's cleaner than a macro...
I'll create the branch as soon as #210 is merged

**Pull request merged**
