### PR TITLE
Move packages

### PR DESCRIPTION
**Pull request by fmessmer**
moved from cob_driver:
- cob_base_velocity_smoother
- cob_collision_velocity_filter
- cob_footprint_observer
- cob_lookat_controller
- cob_trajectory_controller
- cob_twist_controller

### CODE REVIEW

**Comment by abubeck** [comment]
LGTM
only lookat controller has some robot specific config files

**Comment by fmessmer** [comment]
I know.
I will move them in a separate PR once the restructuring is done!

**Comment by floweisshardt** [comment]
visual review: OK

**Comment by NadiaHG** [comment]
Visual Review: OK

**Pull request merged**
