### PR TITLE
Configurable base twist controller

### PR DESCRIPTION
**Pull request by mathias-luedtke**
supersedes #135

### CODE REVIEW

**Comment by mathias-luedtke** [comment]
amended last commit, please reset accordingly

**Comment by mathias-luedtke** [comment]
@ipa-fxm: the yaml values should be now read as config and default

**Comment by fmessmer** [comment]
testing this in indigo-setup again reveals the following issues:
 - ~~the steer joints do not move anymore, steer_target_error is always 0.0, drive joints move~~ (joystick mode was changed :wink:)
 - when changing default/steer_ctrl in dynamic_reconfigure, the values in the wheel-specific dynamic_reconfigure namespace do not update...

**Comment by mathias-luedtke** [comment]
Please try again :)

**Comment by fmessmer** [comment]
Now I cannot even load it anymore:

```
[INFO] [WallTime: 1487340882.887469] ...<<base>> is <<init>>
[ INFO] [1487340882.888024974]: Recover base
[INFO] [WallTime: 1487340882.891096] <<recover>> <<base>>
[INFO] [WallTime: 1487340882.893658] Wait for <<base>> to <<recover>>...
[ INFO] [1487340882.895056755]: Recovering XXX
[INFO] [WallTime: 1487340882.915938] ...<<base>> is <<recover>>
Loaded joint_state_controller
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/controller_manager/controller_manager", line 63, in <module>
    controller_manager_interface.load_controller(c)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/controller_manager/controller_manager_interface.py", line 66, in load_controller
    resp = s.call(LoadControllerRequest(name))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 525, in call
    raise ServiceException("transport error completing service call: %s"%(str(e)))
rospy.service.ServiceException: transport error completing service call: unable to receive data from sender, check sender's logs for details
[base/driver-11] process has died [pid 31862, exit code -11, cmd /u/robot/git/care-o-bot/install/lib/canopen_motor_node/canopen_motor_node __name:=driver __log:=/u/fxm/.ros/log/66803dd8-f51b-11e6-b9b6-f44d3066217f/base-driver-11.log].
log file: /u/fxm/.ros/log/66803dd8-f51b-11e6-b9b6-f44d3066217f/base-driver-11*.log
[base/base_controller_spawner-12] process has died [pid 31864, exit code 1, cmd /opt/ros/indigo/lib/controller_manager/controller_manager spawn joint_state_controller twist_controller odometry_controller __name:=base_controller_spawner __log:=/u/fxm/.ros/log/66803dd8-f51b-11e6-b9b6-f44d3066217f/base-base_controller_spawner-12.log].
log file: /u/fxm/.ros/log/66803dd8-f51b-11e6-b9b6-f44d3066217f/base-base_controller_spawner-12*.log
```

**Pull request closed without merging**
