### PR TITLE
[kinetic] wheel multi controller refactored

### PR DESCRIPTION
**Pull request by mathias-luedtke**
solves https://github.com/ipa320/cob_control/issues/144

supersedes #138

### CODE REVIEW

**Comment by fmessmer** [comment]
needs more testing and investigation on HW regarding the position control of the steer joints as started in #138

**Comment by mathias-luedtke** [comment]
rebased on #141

**Comment by fmessmer** [comment]
Simulation is working under Kinetic (PC setup in my office), thus, we should get back to test and finalize this PR in simulation first...then HW eventually...

**Comment by fmessmer** [comment]
remember to specify `required_drive_modes` for your hardware: https://github.com/ros-industrial/ros_canopen/issues/197

**Comment by fmessmer** [comment]
@ipa-mdl 
I'll merge this...the controller works on cob4-18...we just might need to do some more parmeter tuning...will do this on a new feature PR

**Review by fmessmer — APPROVED** [review]

**Pull request merged**
