### PR TITLE
fix wheel transformation from urdf

### PR DESCRIPTION
**Pull request by benmaidel**
read whole transformation chain between wheel and base_link

### CODE REVIEW

**Review by ipa-rmb — DISMISSED** [review]
Speaking for style. Is the code successfully tested?

**Comment by fmessmer** [comment]
@ipa-rmb 
this is part of something bigger involving several PRs...and a tricycle plattform...please hold

**Comment by benmaidel** [comment]
@ipa-fxm this PR should be fine without any other PR's. This is necessary if the Wheels are not directly connected to the base_link. Like it is done here https://github.com/ipa320/cob_common/pull/245. If they are directly connected, this PR is also fine. It was also tested on the unity base.

**Comment by benmaidel** [comment]
rebased it

**Review by fmessmer — APPROVED** [review]
I guess we can merge this

**Pull request merged**
