### PR TITLE
Configurable base twist controller refactored

### PR DESCRIPTION
**Pull request by mathias-luedtke**
#140 without wheel multi controller, supersedes #137

### CODE REVIEW

**Comment by fmessmer** [comment]
After refactoring, `cob_undercarriage_ctrl_node` does not compile anymore (see [travis](https://travis-ci.org/ipa320/cob_control/builds/202736110))

I mean, the package is going to be obsolete once all raw's use canopen (see https://github.com/ipa320/cob_robots/issues/422), but this still might take a while...

**Comment by fmessmer** [comment]
Well, it seems that `cob_undercarriage_ctrl_node` package is not used at all: 
https://github.com/search?q=org%3Aipa320+cob_undercarriage_ctrl_node&type=Code

Should we just remove the package then? @ipa-mdl

**Comment by mathias-luedtke** [comment]
> Should we just remove the package then?

Let's wait until at least one raw runs with `ros_canopen`.

**Comment by fmessmer** [comment]
the raw's use `cob_undercarriage_ctrl` (from cob_driver) but not `cob_undercarrage_ctrl_node` (from cob_control)
Thus, in order for travis to succeed, we already can remove `cob_undercariiage_ctr_node` package from cob_control

**Comment by fmessmer** [comment]
When testing this with simulation:
```
[ERROR] [1487663693.654953011, 2.190000000]: Could not load class cob_omni_drive_controller/WheelController: Failed to load library /home/fxm/projects/indigo/care-o-bot/devel/lib//libcob_omni_drive_controller.so. Make sure that you are calling the PLUGINLIB_EXPORT_CLASS macro in the library code, and that names are consistent between this macro and your XML. Error string: Could not load library (Poco exception = /home/fxm/projects/indigo/care-o-bot/devel/.private/cob_omni_drive_controller/lib/libcob_omni_drive_geom.so: undefined symbol: _ZN11PosCtrlData5resetEv)
[ERROR] [1487663693.655072828, 2.190000000]: Could not load controller 'twist_controller' because controller type 'cob_omni_drive_controller/WheelController' does not exist.
[ERROR] [1487663693.655110860, 2.190000000]: Use 'rosservice call controller_manager/list_controller_types' to get the available types
Error when loading twist_controller
```

Don't know why? 
All other repos are using `ipa320/indigo_dev`, plugins are known (`rosservice call controller_manager/list_controller_types`), parameters are set correctly...
Does the `init()` fail?

**Comment by mathias-luedtke** [comment]
It's not linked properly..

**Comment by mathias-luedtke** [comment]
just missed your first comment on cob_undercarriage_ctrl_node..
I will try to fix it. If this is too much work, I will remove it.

**Comment by mathias-luedtke** [comment]
linking error should be fixed.. will squash later.

**Comment by fmessmer** [comment]
Loading now works, but dynamic reconfigure is not exposed as it seems that https://github.com/ipa320/cob_control/pull/141/files#diff-ae7c726f9788c4d0c766f5aa435b5724R45 is never called

EDIT:
obviously you return before calling init: https://github.com/ipa320/cob_control/pull/141/files#diff-ae7c726f9788c4d0c766f5aa435b5724R18

`WheelController::init()` should be 
```
    virtual bool init(hardware_interface::VelocityJointInterface* hw, ros::NodeHandle &root_nh, ros::NodeHandle& controller_nh){

        wheel_params_t wheel_params;
        if(!parseWheelParams(wheel_params, controller_nh) || !GeomController::init(hw, wheel_params)) return false;
        if(!setup(root_nh,controller_nh)) return false;
        pos_ctrl_.init(wheel_params, controller_nh);
        return true;
    }
```

**Comment by fmessmer** [comment]
Still two more issues:
 - changing default reconfigure does not update joint-specific reconfigure
 - all joint-specific reconfigure only have an effect on wheel front_right

Investigating...

**Comment by fmessmer** [comment]
> all joint-specific reconfigure only have an effect on wheel front_right

remove the double for loop in `PosCtrl::init()`:
```
            for(size_t i=0; i< pos_ctrl_params.size(); ++i) {
                boost::shared_ptr<dynamic_reconfigure::Server<SteerCtrlConfig> > dr(new dynamic_reconfigure::Server<SteerCtrlConfig>(mutex, ros::NodeHandle(nh, params[i].geom.steer_name)));
                SteerCtrlConfig config;
                copy(config, params[i].pos_ctrl);
                dr->setConfigDefault(config);
                dr->updateConfig(config);
                dr->setCallback(boost::bind(&PosCtrl::setForOne, this, i, _1, _2));  // this writes the joint-specific config into pos_ctrl_params
                reconfigure_server_axes_.push_back(dr);
            }
```

**Comment by fmessmer** [comment]
> changing default reconfigure does not update joint-specific reconfigure

I think we need to update the `reconfigure_server_axes_` reconfigure servers within `PosCtrl::setForAll()` somehow - but atm this is not possible due to mutex lock
```
reconfigure_server_axes_[i]->setConfigDefault(config);
reconfigure_server_axes_[i]->updateConfig(config);
```

**Comment by mathias-luedtke** [comment]
Can you share your simulation config with me?
Or we could work on it together later..

**Comment by mathias-luedtke** [comment]
works for me in simulation.

**Comment by mathias-luedtke** [comment]
needs to be rebase/squashed properly and #140  needs to be updated afterwards

**Review by fmessmer — APPROVED** [review]
tested configurability in simulation..
works as expected :+1: 

@ipa-mdl please go on and squash - I'll merge then

**Comment by fmessmer** [comment]
fixes #91 
@ipa-mig FYI

**Comment by mathias-luedtke** [comment]
> please go on and squash - I'll merge then

@ipa-fxm: done, please test once again

**Comment by fmessmer** [comment]
tested...and still works fine...merging
Thank you @ipa-mdl

**Pull request merged**
