### PR TITLE
use urdf::JointConstSharedPtr instead of boost...

### LINKED ISSUE #181: cob_omni_drive_controller fails to compile with newer urdf versions
Compilation fails because newer urdf uses c++11 shared_ptr for urdf::JointConstSharedPtr

```
/var/tmp/portage/ros-kinetic/cob_omni_drive_controller-0.7.1/work/cob_omni_drive_controller-0.7.1/src/param_parser.cpp: In function ‘bool parseWheelGeom(WheelGeom&, XmlRpc::XmlRpcValue&, MergedXmlRpcStruct&, urdf::Model*)’:
/var/tmp/portage/ros-kinetic/cob_omni_drive_controller-0.7.1/work/cob_omni_drive_controller-0.7.1/src/param_parser.cpp:113:54: error: no match for ‘operator=’ (operand types are ‘boost::shared_ptr<const urdf::Joint>’ and ‘urdf::JointConstSharedPtr {aka std::shared_ptr<const urdf::Joint>}’)
         steer_joint = model->getJoint(geom.steer_name);
                                                      ^
In file included from /usr/include/boost/shared_ptr.hpp:17:0,
                 from /opt/ros/kinetic/include/ros/forwards.h:37,
                 from /opt/ros/kinetic/include/ros/common.h:37,
                 from /opt/ros/kinetic/include/ros/ros.h:43,
                 from /var/tmp/portage/ros-kinetic/cob_omni_drive_controller-0.7.1/work/cob_omni_drive_controller-0.7.1/include/cob_omni_drive_controller/UndercarriageCtrlGeomROS.h:21,
                 from /var/tmp/portage/ros-kinetic/cob_omni_drive_controller-0.7.1/work/cob_omni_drive_controller-0.7.1/src/param_parser.cpp:18:
```

@fmessmer FYI

### PR DESCRIPTION
**Pull request by jabbenseth**
working on melodic this makes the controllers compatible with melodic urdf (types are defined in kinetic as well)

(basically #182 renewed)
fixes #181

### CODE REVIEW

**Review by fmessmer — COMMENTED** [review]
looks good, but I can't tell whether this makes it melodic-compatible...
@ipa-jba could you add melodic jobs to the travis yaml?

**Comment by jabbenseth** [comment]
melodic still fails with some other issues (this is one of them). The trickiest component will be cob_obstacle_distance. I can add checks however (in a separate PR, this one or #202 ?)

**Review by fmessmer — CHANGES_REQUESTED** [review]
please rebase to enable melodic tests in travis

**Review by benmaidel — DISMISSED** [review]
Was also already melodifiing cob packages and recognized your PR's just right now. I've done exactly the same. :)

**Comment by jabbenseth** [comment]
close in favour of #208

**Pull request closed without merging**
