### PR TITLE
[WIP] tricycle fake wheels

### PR DESCRIPTION
**Pull request by fmessmer**
first tries seem promising in hw/in sim

@ipa-fez @ipa-flg could I get some feedback on the kinematics in the new odom plugin
@ipa-mdl any suggestions/improvements for the code structure, e.g. making `wheels_` public...

### CODE REVIEW

**Comment by mathias-luedtke** [comment]
TL;DR: do not merge!

There is no need to add this passive wheel flag at all.
It would be better to use FakeJointHandles, which emulate the passive wheels.

**Comment by fmessmer** [comment]
@ipa-mdl 
I can think of getting rid of the `passive` parameter by parsing the `transmission` tag of the urdf.
I could then decide to use `FakeJointHandle` either if a transmission is not provided at all or if e.g. `FakeJointInterface` is specified in the `hardwareInterface`-tag of the urdf...

But I fear, currently neither `FakeJointHandle` nor `FakeJointInterface` is implemented/supported in `ros_control`...or is it?
Would I really need to copy-paste everything implemented for e.g. `VelocityJointHandle` and `VelocityJointInterface` and then adapt it to provide `Fake`-behavior - or do you see an easier way?

What I would need is some Handle that would return as state what has been set as command - independent from that being position, velocity or effort...

**Comment by mathias-luedtke** [comment]
> Would I really need to copy-paste everything implemented for e.g. VelocityJointHandle and VelocityJointInterface and then adapt it to provide Fake-behavior - or do you see an easier way?

No, but you have to create `VelocityJointHandle` for you fake motors.
FakeJointHandle is just a helper, or perhaps a subclass.

**Comment by fmessmer** [comment]
superseded by #190

**Pull request closed without merging**
