### PR TITLE
fixed cob_trajectory_controller action preemption state in run method, see #14

### LINKED ISSUE #14: cob_trajectory_controller will not stop the arm if follow_joint_traj_action is in preemption state
If an active follow_joint_trajectory action is aborted, the cob_trajectory_controller will never stop the control chain. Indeed he is sending the last set velocity to the driver in a loop.

This error happens if, for example, the moveit trajectory execution monitor stops a trajectory.

### PR DESCRIPTION
**Pull request by benmaidel**
This pull request fixes #14

### CODE REVIEW

**Comment by fmessmer** [comment]
LGTM
Did you also test the behaviour when the stop service (via rosservice call or command_gui) is called?

**Comment by benmaidel** [comment]
Nope, have not tested this. But it should cause the exact same behavior.

**Comment by floweisshardt** [comment]
visual review: Ok

**Comment by fmessmer** [comment]
@ipa-bnm you are right. The `stop` service also sets 

```
executing_ = false;
traj_generator_->isMoving = false;
```

So this PR should be good to merge!

**Pull request merged**
