### PR TITLE
add emulation_clock publisher

### PR DESCRIPTION
**Pull request by fmessmer**
ref mojin-robotics/cob4#1238
better approach than #231 

ToDo:
PR for `melodic_dev`

### CODE REVIEW

**Comment by floweisshardt** [comment]
works basically. The only problem I have on my machine is that setting `emulation_time_factor:=1` (default) results in a slowed down performance compared to not using the clock node (realtime factor drops to 1/2x-1/3x).

I verified that with `rostopic echo /clock` where clock.secs increases slower than realtime. Same can be seen by comparing `ROS Elapsed` and `Wall Elapsed` in Rviz. My system load at this time was quite high (13 for 4 core machine). @fmessmer might that influence the `time.sleep(dt)`?

**Review by floweisshardt — CHANGES_REQUESTED** [review]
works basically. The only problem I have on my machine is that setting `emulation_time_factor:=1` (default) results in a slowed down performance compared to not using the clock node (realtime factor drops to 1/2x-1/3x).

I verified that with `rostopic echo /clock` where clock.secs increases slower than realtime. Same can be seen by comparing `ROS Elapsed` and `Wall Elapsed` in Rviz. My system load at this time was quite high (13 for 4 core machine). @fmessmer might that influence the `time.sleep(dt)`?

**Comment by fmessmer** [comment]
> works basically. The only problem I have on my machine is that setting `emulation_time_factor:=1` (default) results in a slowed down performance compared to not using the clock node (realtime factor drops to 1/2x-1/3x).
> 
> I verified that with `rostopic echo /clock` where clock.secs increases slower than realtime. Same can be seen by comparing `ROS Elapsed` and `Wall Elapsed` in Rviz. My system load at this time was quite high (13 for 4 core machine). @fmessmer might that influence the `time.sleep(dt)`?

@floweisshardt 
that's what I meant when I said that it might not be precise as I do not consider the time the actual loop iteration takes when sleeping for `dt`
I might need to re-implement this using a timer function and then considering event.current_real and event.last_real to calculate actual sleep duration
:point_right: marked as WIP

**Comment by floweisshardt** [comment]
> > works basically. The only problem I have on my machine is that setting `emulation_time_factor:=1` (default) results in a slowed down performance compared to not using the clock node (realtime factor drops to 1/2x-1/3x).
> > I verified that with `rostopic echo /clock` where clock.secs increases slower than realtime. Same can be seen by comparing `ROS Elapsed` and `Wall Elapsed` in Rviz. My system load at this time was quite high (13 for 4 core machine). @fmessmer might that influence the `time.sleep(dt)`?
> 
> @floweisshardt
> that's what I meant when I said that it might not be precise as I do not consider the time the actual loop iteration takes when sleeping for `dt`

I got that. But I expected to have some few 0.0X%-1.0% offset and not 200-300%.

**Comment by floweisshardt** [comment]
just running the clock node with low cpu load is fine. As soon as I start to include the emulator and e.g. navigation the load is to high and decreases the realtime factor. so we should do two things:
- reduce load for emulation (by disabling nodes which are not needed in emulation --> https://github.com/mojin-robotics/cob4/issues/1238)
- using a timer function and then considering event.current_real and event.last_real to calculate actual sleep duration

**Comment by fmessmer** [comment]
@floweisshardt 
I implemented the node with a timer callback and this solves the issue with the discrepancy between `ROS Elapsed` and `Wall Elapsed` - when setting `time_factor` to 1

however, when setting `time_factor` to 10, load is still high (for the emulation_clock node itself, but also for rviz, navigation and other nodes)...which is obvious as those nodes have to do 10x the usual computation...

increasing `dt` to `0.1` instead of `0.01`, reduced the load of course, but introduced other problems as I think the granularity of the clock was too large...

currently, I get the best performance with `dt` set to `0.01` and a `time_factor` of 5...
setting `time_factor` to 10 or larger does not give the nodes enough time to do there job and I see to many warnings of all sorts, e.g. tf lookup exceptions and navigation warnings...

@floweisshardt please retest...any other suggestions for improvements?

**Review by floweisshardt — APPROVED** [review]
works well now.

**Comment by floweisshardt** [comment]
I considder this working and will merge all PRs related to emulation speedup

**Pull request merged**
